# Generated by Django 5.2.1 on 2025-05-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_workerimage_name_alter_worker_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerimage',
            name='name',
        ),
    ]
