# Generated by Django 5.2.1 on 2025-05-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_workerimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='net',
            name='c_name',
            field=models.CharField(default='net', editable=False),
        ),
        migrations.AddField(
            model_name='rolet',
            name='c_name',
            field=models.CharField(default='rolet', editable=False),
        ),
    ]
