# Generated by Django 5.2.1 on 2025-05-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_windowcolour_windowtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='c_name',
            field=models.CharField(default='fabric', editable=False),
        ),
    ]
