# Generated by Django 5.2.1 on 2025-06-01 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_fabric_c_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolet',
            name='price_m',
        ),
    ]
