# Generated by Django 5.2.1 on 2025-06-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_rolet_price_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolet',
            name='price_m',
            field=models.IntegerField(default=0),
        ),
    ]
