# Generated by Django 5.2.1 on 2025-06-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rolet_price_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='net',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='rolet',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
