# Generated by Django 5.2.1 on 2025-06-01 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_fabric_description_alter_net_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabric',
            options={'verbose_name': 'Тканина', 'verbose_name_plural': 'Тканини'},
        ),
        migrations.AlterModelOptions(
            name='net',
            options={'verbose_name': 'Москітна сітка', 'verbose_name_plural': 'Москітні сітки'},
        ),
        migrations.AlterModelOptions(
            name='rolet',
            options={'verbose_name': 'Ролет', 'verbose_name_plural': 'Ролети'},
        ),
        migrations.AlterModelOptions(
            name='windowcolour',
            options={'verbose_name': 'Колір вікна', 'verbose_name_plural': 'Кольори вікон'},
        ),
        migrations.AlterModelOptions(
            name='windowtype',
            options={'verbose_name': 'Тип вікна', 'verbose_name_plural': 'Типи вікон'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Працівник', 'verbose_name_plural': 'Працівники'},
        ),
        migrations.AlterModelOptions(
            name='workerimage',
            options={'verbose_name': 'Фото роботи', 'verbose_name_plural': 'Фото роботи'},
        ),
        migrations.AlterField(
            model_name='fabric',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.ImageField(upload_to='main/fabrics/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='price_m',
            field=models.IntegerField(verbose_name='Ціна за метр'),
        ),
        migrations.AlterField(
            model_name='net',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='net',
            name='image',
            field=models.ImageField(upload_to='main/nets/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='net',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='net',
            name='price',
            field=models.IntegerField(verbose_name='Ціна за встановлення'),
        ),
        migrations.AlterField(
            model_name='net',
            name='price_m',
            field=models.IntegerField(verbose_name='Ціна за метр'),
        ),
        migrations.AlterField(
            model_name='rolet',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='rolet',
            name='fabric',
            field=models.ManyToManyField(to='main.fabric', verbose_name='Доступні тканини'),
        ),
        migrations.AlterField(
            model_name='rolet',
            name='image',
            field=models.ImageField(upload_to='main/rolets/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='rolet',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='rolet',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='rolet',
            name='price_m',
            field=models.IntegerField(default=0, verbose_name='Ціна за метр'),
        ),
        migrations.AlterField(
            model_name='windowcolour',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='windowcolour',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='windowtype',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='windowtype',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(upload_to='main/workers', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='workerimage',
            name='work_picture',
            field=models.ImageField(upload_to='main/workers_work', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='workerimage',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker', verbose_name='Працівник'),
        ),
    ]
